# Use an existing docker image as a base
FROM alpine

# Download and install a dependency
RUN apk add --update gcc
RUN apk add --update redis

# Tell the im age to do what it starts
# as a container
cmd ["redis-server"]

